language: node_js
notifications:
  email: raphael.aolima8@gmail.com
node_js:
- 0.10
services:
- mongodb
env:
  global:
  - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
- npm install -g bower@1.3
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_deploy:
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"
- git checkout $TRAVIS_BRANCH
- git add .
- git commit -m "Travis commit"
before_script:
- node test/data.js
- grunt minifica
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- node server &
- protractor config/protractor.js
deploy:
  provider: openshift
  user: raphael.aolima8@gmail.com
  password:
    secure: W8c9m0iuuQ/2wTcAPi49NwgSWiGu1xMs5oNYhVUWR0tO3GWcxabNL6iEtEL9DkWConyS7gtB16v4FgF+qeKy58qbgSltdTnzHWx/c9ENUkAxTl2wP0CHaim2eiLlN3MDvE4NZb6DyWAXHEGKwHrXjUMlKIucYLjpioAsenaCuycF5R6QegGf3WmbZVhKmNGA4QThueAv69HZV16cx6KK2AQnePKKXMDP5ny5iXAJ4vaRRHjlPL3byWdUH4JFRutewAQclP0rqAoAt1Ifxti6Ye/u9R6Gx57LWOZYMvdXEq4SEGABYobyi8vMBGWQrlbzs3SftCOBCz1BbBgFKOYsQYmJYJN+fK3Z1uECTbNWyRkCZgAucGuhWxPXFGDrsJDqv7plF158INTFl8H6rlIBdRo0rrCJpEox8bELfoV2r/TSvw60DUPdJrLf2zJt4fYH3onRsLxeyq+X9ao3Y7rXbqefneN7L2AVTZqsmhM6QlZpiYKLdBCErSC3aZmiqB0BfPMAdIOAJSHVr7MaVZ7SFmMr9AFZgaj4sBu8GhbZyJ10OcplKqoSGNfYS9mtG9uKE/D+zlDVFQ9QuT+La+farW7K7ZUqPfxar+YMWgvMLGIJQiKhdGlpFJh9qAr68TRgI0Yv3/OYRS3xZ992+dJwF5ekx8stO4HK11PRJjFhSoY=
  app: mean
  domain: raphaellima
  on:
    repo: raphaellima8/mean
