language: node_js
notifications:
  email: raphael.aolima8@gmail.com
node_js:
- 0.10
services:
- mongodb
env:
  global:
  - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
- npm install -g bower@1.7
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
before_deploy:
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"
- git checkout $TRAVIS_BRANCH
- git add .
- git commit -m "Travis commit"
before_script:
- node test/data.js
- grunt minifica
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- node server &
- protractor config/protractor.js
deploy:
  provider: openshift
  user: shd.contato@gmail.com
  password:
    secure: 
  app: nodemean
  domain: raphaellima8
  on:
    repo: raphaellima8/mean
